server:
  port: 8888

spring:
  application:
    name: config-server-discovery
  cloud:
    config:
      server:
        git:
          uri: https://github.com/haikubabe/config-repo.git

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka