spring:
  application:
    name: gateway-service

ribbon:
  eureka:
    enabled: false

zuul:
  routes:
    hello-service:
      url: http://localhost:1111
    goodbye-service:
      url: http://localhost:2222